### ISSUE TITLE
`XmlExtensions.ForLoop` is broken when `increment` is negative...

### ISSUE THREAD

**Issue by slippycheeze** [15adhami/XmlExtensions#15]
https://github.com/15adhami/XmlExtensions/blob/78f15cc5e117915ede98ccca9253f75ed7562bd7/Source/PatchOperations/Control/ForLoop.cs#L34

In the code you have `i -= increment` when `increment < 0`, which means that give `from = 3, to = 1, increment = -1` the evaluation will be:
 * `i = from - 1`, so `i = 2`
 * `i >= to`, so `i >= 1`, which is true, so
 * `i -= increment`, so `i -= -1`, which is the same as `i + 1`, so now `i = 3`...

You need to use `for (i = ...; ...; i += increment) {` or make increment absolute to use `-=` there. :)

PS: this seems like it doesn't get much use, which is fair, because it turns out to be very painful for what I wanted.

My use case was "merge duplicate <comps> nodes under an element, handling the case where three separate (stupid) mods blindly added their own <comps> node, generically."  Which is maybe my own fault for being generic, but YOLO, I guess?

Anyway, what I wanted was:

```xml
  <li Class="XmlExtensions.CumulativeMath">
    <xpath>Defs/ThingDef[defName="AncientSystemRack"]/comps</xpath>
    <operation>count</operation>
    <storeIn>count</storeIn>
    <apply>
      <Operation Class="XmlExtensions.ForLoop">
        <from>{count}</from>
        <to>1</to>
        <increment>-1</increment>
        <apply>
          <Operation Class="XmlExtensions.Log">
            <text>[SlippyCheeze] want to merge comps list {i} of {count}</text>
            <xpath>Defs/ThingDef[defName="AncientSystemRack"]/comps[{i}]</xpath>
          </Operation>
        </apply>
      </Operation>
    </apply>
  </li>
```

as in, if I found 3 `<comps>` then loop with `i = 3, 2`, so that I could merge them in reverse order.  *shrug*

**Comment by 15adhami** [comment]
Thank you for reporting this issue, it has been fixed in the latest release on Steam; I also changed how it behaves a bit to make it more consistent. Yeah, I couldn't even think of any use cases for this patch operation honestly, but I added it just in case someone might need it.

Based on your use-case I also added a new "PatchOperationRemoveDuplicateNodes". This should hopefully make it simpler for you; let me know if there are any issues or if it can't apply to your use-case exactly.
