### ISSUE TITLE
Helpers.SelectSingleNode() can pass `null` to `PatchManager.ModPatchedDef` as `string name`, which causes exception

### ISSUE THREAD

**Issue by slippycheeze** [15adhami/XmlExtensions#16]
https://github.com/15adhami/XmlExtensions/blob/78f15cc5e117915ede98ccca9253f75ed7562bd7/Source/Core/Helpers.cs#L421-L429

```c#
            XmlNode node = xml.SelectSingleNode(path);
```

This will return `null` if there is no matching node.  If advanced debugging is on then `GetDefNameFromNode` returns `null` given a `null` node, which is then passed to `PatchManager.ModPatchedDef` as the `name` argument, and in turn that is looked up in a dictionary that fails in the face of a `null` key in

```c#
            if (!DefModDict.ContainsKey(name))
```

I'd fix it by passing something appropriate if the `SelectSingleNode` return value was null, but I'm honestly not sure what the best fix is or I'd have thrown you a pull request instead.

**Comment by slippycheeze** [comment]
An easy reproduction:
```xml
  <Operation Class="XmlExtensions.GetName">
    <xpath>Defs</xpath>
    <storeIn>FOO</storeIn>
    <apply>
      <Operation Class="XmlExtensions.Log">
        <text>Got the name [{FOO}]</text>
      </Operation>
    </apply>
  </Operation>
```

Oddly enough, it actually *does* get the name correctly, it just blows up if advanced debugging is enabled. :)

**Comment by 15adhami** [comment]
Thank you for reporting another issue. It has been fixed in the latest release. Also thank you for looking into the issue and pinpointing the problem; hope the code wasn't too messy to navigate.

The problem actually wasn't that the node being passed into `Helpers.GetDefNameFromNode` was null, it actually passed the correct `<Defs>` node that you were searching for. But because this node doesn't have a defName or a Name attribute, the method returns `null` for the name (the point of the method is to find the defName or the Name attribute for a given node). Therefore the solution is to make sure that `name != null` before calling `PatchManager.ModPatchedDef`; since if `name == null`, then it means that we didn't actually patch a Def and the method shouldn't be called (this method is called every time a mod applies a patch operation on a Def). Or more simply, within `PatchManager.ModPatchedDef` we can immediately return if `name == null` (which is what I just added in the latest update). I also fixed another minor issue within `Helpers.SelectSingleNode` that I found.
